require: rubocop-rspec

inherit_from: .oct_rubocop.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'

Capybara/FeatureMethods:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/simply/web/test/**/*'
    - 'spec/spec_helper.rb'

Metrics/LineLength:
  Exclude:
    - 'Rakefile'
  IgnoredPatterns: ['description *= .*']

Metrics/MethodLength:
  Exclude:
    - 'spec/simply/web/helper/setup.rb'
    - 'Rakefile'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
